<template>
<table width="575px;" style="text-align:center;table-layout:fixed;margin-left:175px;" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td colspan="6" style="background:#f3f3f3;border-top:1px solid #ddd;font-size:15px;height:35px;line-height:35px;">
                <b>变频压缩机测试工况参数表</b>
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>测试工况</b>
            </td>
            <td>
                <b>冷凝温度</b>
            </td>
            <td>
                <b>蒸发温度</b>
            </td>
            <td>
                <b>过冷度</b>
            </td>
            <td>
                <b>过热度</b>
            </td>
            <td>
                <b>环境温度</b>
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>ASHRAE/T</b>
            </td>
            <td>
                54.4
            </td>
            <td>
                7.2
            </td>
            <td>
                8.3
            </td>
            <td>
                27.8
            </td>
            <td>
                35
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>高效工况</b>
            </td>
            <td>
                46
            </td>
            <td>
                7.2
            </td>
            <td>
                8.3
            </td>
            <td>
                11.1
            </td>
            <td>
                35
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>'冷房定格</b>
            </td>
            <td>
                45
            </td>
            <td>
                7.2
            </td>
            <td>
                8.3
            </td>
            <td>
                11.1
            </td>
            <td>
                35
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>'冷房中间</b>
            </td>
            <td>
                40
            </td>
            <td>
                15
            </td>
            <td>
                8.3
            </td>
            <td>
                11.1
            </td>
            <td>
                35
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>'暖房定格</b>
            </td>
            <td>
                50
            </td>
            <td>
                -2
            </td>
            <td>
                8.3
            </td>
            <td>
                12.1
            </td>
            <td>
                7
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>'暖房中间</b>
            </td>
            <td>
                35
            </td>
            <td>
                1
            </td>
            <td>
                8.3
            </td>
            <td>
                13.1
            </td>
            <td>
                7
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>'低温制热</b>
            </td>
            <td>
                55
            </td>
            <td>
                -6.8
            </td>
            <td>
                8.3
            </td>
            <td>
                12.1
            </td>
            <td>
                7
            </td>
        </tr>
        <tr class="tm-table">
            <td>
                <b>最大制冷</b>
            </td>
            <td>
                55
            </td>
            <td>
                2
            </td>
            <td>
                8.3
            </td>
            <td>
                11.1
            </td>
            <td>
                35
            </td>
        </tr>
    </tbody>
</table>
</template>
<script>
</script>
<style scoped>

</style>